### ISSUE TITLE
Bundle analyzer as a packageJson script suggestion

### ISSUE THREAD

**Issue by Pickra** [larkintuckerllc/webpack-patterns#1]
Nice work on the tutorial/article. As I was looking through your webpack config, I noticed you're commenting out the [bundle analyzer](https://github.com/larkintuckerllc/webpack-patterns/blob/ac9bc489a48b1b50b6e0a77ebeb54def0cff5b88/react-system-import/webpack.config.js#L118). You can make a packageJson script instead...
`"analyze": " npm run build -- --env.analyze"`
...extract your plugins into a variable and add a conditional that pushes the analyzer into the plugins if `env.analyze` is  true at the top of your `exports.module` function.

```
const plugins = array of plugins
module.exports = env => {
  if (env.analyze) { plugins.push(analyzerPlugin); }

// Other stuff
  plugins: plugins
}
```

Just a suggestion.

**Comment by larkintuckerllc** [comment]
Went ahead and took your advice and updated repository (just the final webpack example, react-system-import).  Also updated the final Medium article to reflect this change.  Thanks for the advice; in hindsight it seems like an obvious improvement.
